class AddProject {
  String area;
  String projectName;
  String projectType;
  String developerName;
  double landParcel;
  String landmark;
  String areaIn;
  String waterSupply;
  int lifts;
  int floors;
  int flatsPerFloors;
  int totalUnit;
  int availableUnit;
  String amenities;
  String parking;
  double longitude;
  double latitude;
  bool transport;
  bool readyToMove;
  bool power;
  bool goods;
  DateTime rera;
  DateTime possession;
  String contactPerson;
  int contactNumber;
  int marketValue;
  double brokerage;
  int incentive;
  double bhk;
  int carpetArea;
  int price;
  List<Map<String, dynamic>> units;

  AddProject(
      {required this.area,
      required this.projectName,
      required this.projectType,
      required this.developerName,
      required this.landParcel,
      required this.landmark,
      required this.areaIn,
      required this.waterSupply,
      required this.lifts,
      required this.floors,
      required this.flatsPerFloors,
      required this.totalUnit,
      required this.availableUnit,
      required this.amenities,
      required this.parking,
      required this.longitude,
      required this.latitude,
      required this.transport,
      required this.readyToMove,
      required this.power,
      required this.goods,
      required this.rera,
      required this.possession,
      required this.contactPerson,
      required this.contactNumber,
      required this.marketValue,
      required this.brokerage,
      required this.incentive,
      required this.bhk,
      required this.carpetArea,
      required this.price,
      required this.units});

  Map<String, dynamic> toMap() {
    return {
      'area': area,
      'projectName': projectName,
      'projectType': projectType,
      'developerName': developerName,
      'landParcel': landParcel,
      'landmark': landmark,
      'areaIn': areaIn,
      'waterSupply': waterSupply,
      'lifts': lifts,
      'floors': floors,
      'flatsPerFloors': flatsPerFloors,
      'totalUnit': totalUnit,
      'availableUnit': availableUnit,
      'amenities': amenities,
      'parking': parking,
      'longitude': longitude,
      'latitude': latitude,
      'transport': transport,
      'readyToMove': readyToMove,
      'power': power,
      'goods': goods,
      'rera': rera.toIso8601String(),
      'possession': possession.toIso8601String(),
      'contactPerson': contactPerson,
      'contactNumber': contactNumber,
      'marketValue': marketValue,
      'brokerage': brokerage,
      'incentive': incentive,
      'bhk': bhk,
      'carpetArea': carpetArea,
      'price': price,
      'units': units
    };
  }
}
